name: Build Android APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle' # YAHAN MAGIC HAI: Ye line Android build ko 2x fast kar degi pichla data use karke

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: |
          flutter pub get || (sleep 5 && flutter pub get)

      # NAYA STEP: Ye step ek khali .env file banayega taaki build crash na ho
      - name: Create dummy .env file
        run: touch .env

      # Yahan --profile add kiya gaya hai
      - name: Build APK
        run: flutter build apk --profile --no-tree-shake-icons

      # Yahan path mein app-profile.apk update kiya gaya hai
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BlueBubbles-App-APK
          path: build/app/outputs/flutter-apk/app-profile.apk
          
