name: Build Android APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # Yahan sabse bada change kiya hai taaki dependency error na aaye
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: |
          flutter pub get || (sleep 5 && flutter pub get) # Retry logic agar network issue ho

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BlueBubbles-App-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          
